name: financeiro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: 3.0.0
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.0
  dio: ^5.3.0
  dropdown_button2: ^2.3.7
  extended_masked_text: ^2.3.1
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_cache_manager: ^3.3.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  form_builder_validators: ^9.0.0
  form_field_validator: ^1.1.0
  from_css_color: 2.0.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  intl: 0.18.1
  json_path: ^0.6.6
  mask_text_input_formatter: ^2.5.0
  page_transition: ^2.1.0
  path_provider: ^2.1.1
  path_provider_android: ^2.2.1
  path_provider_foundation: ^2.3.1
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.7
  provider: ^6.1.1
  shared_preferences: ^2.2.0
  sprung: ^3.0.1
  sqflite: ^2.3.0
  stream_transform: 2.1.0
  timeago: ^3.6.0
  url_launcher: ^6.2.1
  url_launcher_android: ^6.2.0
  url_launcher_ios: ^6.2.1
  url_launcher_platform_interface: ^2.2.0
  url_strategy: ^0.2.0
  uuid: ^4.2.1
  window_location_href: any
  flutter_dotenv: ^5.0.2
  flutter_fancy_tree_view: ^1.4.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_timer_countdown: ^1.0.7
  animate_do: ^3.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - .env

  #fonts:
  #  - family: CustomIcons
  #    fonts:
  #      - asset: assets/fonts/CustomIcons.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
